name: Build and Publish Docker Images
on:
  push:
    branches: [main]
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mahmoud00thedev  # Your username hardcoded
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  # Still use secret for token

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front-end-nextjs
          file: ./front-end-nextjs/Dockerfile
          push: true
          tags: mahmoud00thedev/devops-qr-code-frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: mahmoud00thedev/devops-qr-code-backend:latest